import matplotlib.pyplot as plt

def create_pdf(subject, polished, signature, logo_path=None, word_count=None, analysis=None):
    pdf = FPDF()
    pdf.add_page()

    # Add logo if provided and exists
    if logo_path and os.path.exists(logo_path):
        pdf.image(logo_path, x=10, y=8, w=30)
        pdf.ln(20)

    # Header
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="AI Email Tone Polisher Report", ln=True, align="C")
    pdf.ln(10)

    # Body
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Subject: {subject}", ln=True)
    pdf.multi_cell(0, 10, polished)
    pdf.ln(10)
    pdf.multi_cell(0, 10, signature)

    # --- Analytics Charts ---
    if word_count:
        # Word count bar chart
        fig, ax = plt.subplots()
        ax.bar(["Word Count"], [word_count], color="skyblue")
        ax.set_ylabel("Words")
        ax.set_title("Email Word Count")
        chart_path = "wordcount.png"
        fig.savefig(chart_path)
        plt.close(fig)
        pdf.add_page()
        pdf.image(chart_path, x=30, y=50, w=150)

    if analysis:
        # Tone distribution pie chart
        labels = [analysis['label'], "Other"]
        sizes = [analysis['score']*100, (1-analysis['score'])*100]
        fig2, ax2 = plt.subplots()
        ax2.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
        ax2.axis("equal")
        chart_path2 = "tone.png"
        fig2.savefig(chart_path2)
        plt.close(fig2)
        pdf.add_page()
        pdf.image(chart_path2, x=30, y=50, w=150)

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by AI Email Tone Polisher", 0, 0, 'C')

    return pdf.output(dest="S").encode("latin-1")

